In [10]:
# Import necessary libraries
import pandas as pd
import numpy as np
import os

data = pd.read_csv("/workspaces/bakery_sales_prediction/0_DataPreparation/00_data/data_long.csv")
# Ensure the data is sorted by date
#data = data.sort_values(by='Datum')

# ohne VPI, Number of Ships, Heimspiel probieren 
data = data.drop(columns=["VPI", "Number_of_ships", "Heimspiel", "Warengruppe_2", "Warengruppe_3", "Warengruppe_4", "Warengruppe_5", "Warengruppe_6"])
data = data[data["Warengruppe_1"] == 1]
data.head()  # Print first few rows to verify

,Datum,Umsatz,Warengruppe_1,Temp_Very_Cold,Temp_Cold,Temp_Mild,Temp_Warm,Temp_Hot,Cloud_Clear,Cloud_Partly_Cloudy,...,Donnerstag,Freitag,Samstag,Sonntag,Ship,Feiertag,is_holiday,Weihnachtsmarkt,Markt,Ostertag
0,2013-07-01,148.828353,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,2013-07-02,159.793757,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
2,2013-07-03,111.885594,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,2013-07-04,168.864941,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
4,2013-07-05,171.280754,1,0,0,1,0,0,0,1,...,0,1,0,0,1,0,1,0,0,0

In [11]:
# Data Preparation
# Handle missing values by removing rows with any missing values
data = data.dropna()

# Data split Zeitreihen
# Define your date thresholds
train_end_date = '2017-07-31'
validation_end_date = '2018-07-31'

# Split the data based on the date thresholds
train_data = data[data['Datum'] <= train_end_date]
vali_data = data[(data['Datum'] > train_end_date) & (data['Datum'] <= validation_end_date)]
test_data = data[data['Datum'] > validation_end_date]

# Check the dimensions of the datasets
print("Training dataset dimensions:", train_data.shape)
print("Validation dataset dimensions:", vali_data.shape)
print("Test dataset dimensions:", test_data.shape)

# Separating features and labels
training_features = train_data.drop('Umsatz', axis=1).drop('Datum', axis=1)
validation_features = vali_data.drop('Umsatz', axis=1).drop('Datum', axis=1)
test_features = test_data.drop('Umsatz', axis=1).drop('Datum', axis=1)

training_labels = train_data[['Umsatz']]
validation_labels = vali_data[['Umsatz']]
test_labels = test_data[['Umsatz']]

# Print dimensions of the dataframes
print()
print()
print("Training features dimensions:", training_features.shape)
print("Validation features dimensions:", validation_features.shape)
print("Test features dimensions:", test_features.shape)
print()
print("Training labels dimensions:", training_labels.shape)
print("Validation labels dimensions:", validation_labels.shape)
print("Test labels dimensions:", test_labels.shape)

Training dataset dimensions: (1462, 32)
Validation dataset dimensions: (357, 32)
Test dataset dimensions: (0, 32)


Training features dimensions: (1462, 30)
Validation features dimensions: (357, 30)
Test features dimensions: (0, 30)

Training labels dimensions: (1462, 1)
Validation labels dimensions: (357, 1)
Test labels dimensions: (0, 1)

In [12]:
# Create subdirectory for the pickle files
subdirectory = "pickle_data_Brot"
os.makedirs(subdirectory, exist_ok=True)

# Export of the prepared data to subdirectory as pickle files
training_features.to_pickle(f"{subdirectory}/training_features.pkl")
validation_features.to_pickle(f"{subdirectory}/validation_features.pkl")
test_features.to_pickle(f"{subdirectory}/test_features.pkl")
training_labels.to_pickle(f"{subdirectory}/training_labels.pkl")
validation_labels.to_pickle(f"{subdirectory}/validation_labels.pkl")
test_labels.to_pickle(f"{subdirectory}/test_labels.pkl")