### Import Libraries and Data

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import os

# Import Data
training_data = pd.read_csv('/workspaces/bakery_sales_prediction/0_DataPreparation/00_data/Trainingsdaten_long.csv')
validation_data = pd.read_csv('/workspaces/bakery_sales_prediction/0_DataPreparation/00_data/Validierungsdaten_long.csv')
test_data = pd.read_csv('/workspaces/bakery_sales_prediction/0_DataPreparation/00_data/Testdaten.csv')
test_data

,id,Datum,Warengruppe_1,Warengruppe_2,Warengruppe_3,Warengruppe_4,Warengruppe_5,Warengruppe_6,Temp_Very_Cold,Temp_Cold,...,Markt,Ostertag,Silvester,wetter_sehr_schön,wetter_sehr_schlecht,Frühling,Sommer,Herbst,Winter,Werktag
0,1808011,2018-08-01,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
1,1808021,2018-08-02,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
2,1808031,2018-08-03,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
3,1808041,2018-08-04,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
4,1808051,2018-08-05,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1825,1812226,2018-12-22,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
1826,1812236,2018-12-23,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
1827,1812246,2018-12-24,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,1
1828,1812276,2018-12-27,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,1
1829,1812286,2018-12-28,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,1

### Data Preparation

### Selection of Training, Validation and Test Data

In [2]:
# Separating features and labels
training_features = training_data.drop('Umsatz', axis=1).drop('Datum', axis=1)
validation_features = validation_data.drop('Umsatz', axis=1).drop('Datum', axis=1)
test_features = test_data.drop('id', axis=1).drop('Datum', axis=1)

training_labels = training_data[['Umsatz']]
validation_labels = validation_data[['Umsatz']]
#test_labels = test_data[['price']]

# Print dimensions of the dataframes
print("Training features dimensions:", training_features.shape)
print("Validation features dimensions:", validation_features.shape)
print("Test features dimensions:", test_features.shape)
print()
print("Training labels dimensions:", training_labels.shape)
print("Validation labels dimensions:", validation_labels.shape)
#print("Test labels dimensions:", test_labels.shape)

Training features dimensions: (7493, 46)
Validation features dimensions: (1841, 46)
Test features dimensions: (1830, 46)

Training labels dimensions: (7493, 1)
Validation labels dimensions: (1841, 1)

#### Data Export

In [3]:
# Create subdirectory for the pickle files
subdirectory = "pickle_data"
os.makedirs(subdirectory, exist_ok=True)

# Export of the prepared data to subdirectory as pickle files
training_features.to_pickle(f"{subdirectory}/training_features.pkl")
validation_features.to_pickle(f"{subdirectory}/validation_features.pkl")
test_features.to_pickle(f"{subdirectory}/test_features.pkl")
training_labels.to_pickle(f"{subdirectory}/training_labels.pkl")
validation_labels.to_pickle(f"{subdirectory}/validation_labels.pkl")
#test_labels.to_pickle(f"{subdirectory}/test_labels.pkl")